version: "2"
run:
  tests: true
output:
  show-stats: false
  formats:
    text:
      print-issued-lines: false
      colors: true
linters:
  default: all
  disable:
    - cyclop
    - depguard
    - dupword
    - err113
    - errname
    - errorlint
    - exhaustruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gochecknoglobals
    - gocognit
    - gocritic
    - gocyclo
    - godot
    - godox
    - gomoddirectives
    - ireturn
    - lll
    - maintidx
    - mnd
    - nakedret
    - nestif
    - nilnil
    - nlreturn
    - nolintlint
    - nonamedreturns
    - paralleltest
    - perfsprint
    - predeclared
    - recvcheck
    - revive
    - testpackage
    - unused
    - varnamelen
    - wastedassign
    - whitespace
    - wrapcheck
    - wsl
    - wsl_v5
    - funcorder
    - noinlineerr
    - tagalign
  settings:
    dupl:
      threshold: 100
    exhaustive:
      default-signifies-exhaustive: true
    goconst:
      min-len: 8
      min-occurrences: 3
    gocyclo:
      min-complexity: 10
  exclusions:
    generated: lax
    rules:
      - path: (.+)\.go$
        text: "^(G104|G204|G307):"
      - path: (.+)\.go$
        text: Error return value of .(.*\.Help|.*\.MarkFlagRequired|(os\.)?std(out|err)\..*|.*Close|.*Flush|os\.Remove(All)?|.*printf?|os\.(Un)?Setenv). is not checked
      - path: (.+)\.go$
        text: exported method `(.*\.MarshalJSON|.*\.UnmarshalJSON|.*\.EntityURN|.*\.GoString|.*\.Pos)` should have comment or be unexported
      - path: (.+)\.go$
        text: uses unkeyed fields
      - path: (.+)\.go$
        text: declaration of "err" shadows declaration
      - path: (.+)\.go$
        text: bad syntax for struct tag key
      - path: (.+)\.go$
        text: bad syntax for struct tag pair
      - path: (.+)\.go$
        text: ^ST1012
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
