services:
  postgres:
    image: postgres:17.5
    command: postgres
    user: postgres
    # For local debugging
    # -c logging_collector=on -c log_destination=stderr -c log_directory=/logs -c log_statement=all
    # volumes:
    #   - ./logs:/logs
    restart: always
    environment:
      POSTGRES_PASSWORD: secret
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 1s
      timeout: 60s
      retries: 60
      start_period: 80s
  mysql:
    image: mysql:9.4.0
    command: mysqld
    user: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -psecret"]
      interval: 1s
      timeout: 60s
      retries: 60
      start_period: 80s
